name: Python Application CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs that run in the workflow
jobs:
  build:

    # Define the virtual machine environment for running the job
    runs-on: ubuntu-latest

    # Steps define what the job will do
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil npyscreen tqdm

    - name: Run speed test script
      run: |
        python path/to/your/script.py

    # Optional: Add linting or other quality checks
    - name: Run lint
      run: |
        pip install flake8
        flake8 path/to/your/script.py

    # Optional: Cache pip dependencies for faster builds in future
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Optional: Save log files as artifacts for review
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: ./logs
